# Generated by Django 3.2 on 2021-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calories',
            new_name='serving',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='food',
            name='servingAs',
            field=models.CharField(default='serving', max_length=50),
            preserve_default=False,
        ),
    ]
