# Generated by Django 3.2 on 2021-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210415_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
