# Generated by Django 3.2 on 2021-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_auto_20210416_1451'),
        ('foods', '0004_alter_food_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='logbook',
            field=models.ManyToManyField(related_name='logbooks', to='logbook.Logbook'),
        ),
    ]
