# Generated by Django 3.2 on 2021-04-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_auto_20210416_1451'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='logbook.logbook'),
            preserve_default=False,
        ),
    ]
