# Generated by Django 3.2 on 2021-04-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_diary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='diary',
            new_name='logbook',
        ),
    ]
