# Generated by Django 3.2 on 2021-04-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_remove_user_logbook'),
        ('logbook', '0004_auto_20210416_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
